title: Doctoral profile
logo: /assets/img/logo.png
description: PhD student in Mathematics at the University of Bath 
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
![Charlie Cameron](assets/img/IMG_1163.jpeg){: style="max-width: 200px; border-radius: 50%;" }
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


